### ISSUE TITLE
TODO 정리

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#108]
### 디자인
- [x] 기록 - 루틴 페이지
- [x] 그룹 - 운동 인증 페이지
- [x] 그룹 목록에 그룹이 없을 경우 대체 텍스트 표시
- [x] #107 

### 기능
- [x] 그룹 seed 함수
- [x] 그룹 탈퇴에 confirm 추가
- [x] GroupCert 테스트 코드
- [x] 추가한 seed 함수들을 wiki Home에 추가

### 버그
- [x] 그룹 운동 인증에서, 다른 날짜를 클릭하고 다시 오늘로 돌아와도 '완료' 버튼이 회색으로 남음
- [x] 회색으로 뜨는 '완료' 버튼을 눌러도 운동 인증이 작동함
- [x] 지난 달의 날짜를 클릭하면 '완료' 버튼이 초록색으로 뜸

### Deployment
- [x] Https 도메인 배포 성공
- [x] 이미지 업로드
- [x] 웹소켓 연결
- [x] 지도 API 연결
- [x] 유튜브 API 연결
- [x] 소셜 로그인 연결
- [x] 최종 기능 테스트
- [x] README 작성 (로컬 및 배포 버전)

### Assignment
- [x] Final Docs (Requirements and Specification, Design and Planning, Progress Report)
- [x] Poster
- [x] Final Report

**Comment by KJYoung** [comment]
@jihyungKo 루틴을 만든 이후에 그걸 불러오는 기능이 아직 없는 것 같은데 맞나요? 그렇다면 그것도 위 Todo에 포함시켜서 하면 좋을 것 같습니다..!

**Comment by seuha516** [comment]
@jihyungKo seed 함수들을 wiki 홈에 추가해 주세요.

**Comment by jihyungKo** [comment]
> @jihyungKo seed 함수들을 wiki 홈에 추가해 주세요.

추가했습니다!

**Comment by seuha516** [comment]
@KJYoung 

![image](https://user-images.githubusercontent.com/79067549/205923535-ddd4190e-f2c8-4c32-81da-813bd6ab7c28.png)

운동정보를 클릭했을 때 가끔씩 500 에러가 뜹니다.
같은 클릭의 경우에도 될 때가 있고 안 될 때가 있네요

**Comment by KJYoung** [comment]
@seuha516  저도 문제는 확인했고, 아마 저희 AWS 서버가 네트워크가 느려서? 유튜브에서 정보 가져올 때 timeout 류의 문제가 나는게 아닐까 싶은데 지금 deploy된 저 서버의 로그를 볼 수가 있을까요?

**Comment by seuha516** [comment]
@jihyungKo 
![image](https://user-images.githubusercontent.com/79067549/205931057-5dd514f2-f8d3-4d78-80b4-8e18e519cfcb.png)
seed_logs에서 이 오류가 뜨는데 확인 부탁드릴게요

**Comment by jihyungKo** [comment]
@seuha516 호옥시 tag 생성 잘 되어있는지 확인 부탁드려도 될까요??

**Comment by seuha516** [comment]
> @seuha516 호옥시 tag 생성 잘 되어있는지 확인 부탁드려도 될까요??

해결했습니다! prepare_tag가 mysql이랑 조금 안 맞아서 실행이 제대로 안 됐었네요
