### ISSUE TITLE
Community - Backlogs

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#40]
(임시) 다음 PR이 생성되면 옮길 예정입니다.
## Tasks
- [ ] Representative Tag
- [ ] Tag Deletion
- [ ] Scrap
- [ ] Optimize(Like, Dislike Post)
- [ ] Write tests!!!
- [ ] Tag Automatic generation
- [ ] Connect with Information Page
- [ ] Information Page Crawling

## Backlog
- Places : MapAPI
- Places : MachineAPI
- Tags : Workout name API
- Information : How..?
- User Avatar popup.
- Tag Select Customization
- Sidebar contents?
- Level Visualizer
