### ISSUE TITLE
[FEAT] Todo List for Sprint 4

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#51]
- [x] 그룹 채팅방
- [x] Header에 장소 카테고리 추가
- [x] Mypage UI 개선
- [x] 경험치 및 레벨 시스템 구현
- [x] 유저 정보 + 팝업 컴포넌트
- [x] 알림 시스템 구현

**Comment by seuha516** [comment]
스프린트 4 마무리 작업

- [x] 이미지 확장자 선택 제한
- [x] 이미지 용량 제한
- [x] 웹소켓 관련 테스트 코드
- [x] 팝업 모달에 채팅 기능 연결
- [x] 알림 아이콘에 숫자 표시 추가
