### ISSUE TITLE
[FEAT] sprint4 todo list

### ISSUE THREAD

**Issue by blackruby02** [swsnu/swppfall2022-team4#56]
<Group 고도화>
- [x] sprint2 내용 리팩토링
- [x] 프론트 제약 백엔드에도 적용하기
- [ ] Group Edit 만들기
- [x] 그룹 상세 페이지 헤더 만들기
- [x] 그룹장 위임 기능 만들기
- [x] 검색기능

<장소>
- [x] 장소 api 가져오기
- [x] Group List 에서 유저 위치 띄우기
- [x] Group List 정렬 기능(최신, 오래된 순, 가까운 순)
- [x] 장소를 통한 그룹 만들기
- [x] Group List에 장소 주소명으로 띄우기

<인증>
- [x] 운동 인증 백엔드 구현
- [x] 운동 인증 페이지 만들기
- [x] 운동 인증 멤버랑 연동

<maybe?>
- [ ] 그룹 가입 허가 알림
- [ ] 비공개 그룹?
