### ISSUE TITLE
[FEAT] Tag, Community & Information Backlog 

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#79]
## TODO in #99 
- [x] 정보페이지 로비
- [x] Paginator 디자인
- [x] 태그 랭킹 디자인
- [x] 전반적인 디자인
- [x] Test
- [x] Refactor
- [x] Post Routine 연결
- [x] Post Group 연결
- [x] Info Group 연결

**Comment by KJYoung** [comment]
## Done in https://github.com/swsnu/swppfall2022-team4/pull/92
- [x] FitElement 개선 => 통합을 위해
- [x] Tag Modal 윗부분 배경 해결
- [x] 태그 이름 빠짐
- [x] 카테고리 생성을 위로
- [x] 댓글 엔터 제출
- [x] Group Tag
- [x] PostMain Layout ( https://github.com/swsnu/swppfall2022-team4/issues/90 )
- [x] Social Login ( https://github.com/swsnu/swppfall2022-team4/issues/90 )
- [x] 그룹 게시글
- [x] Group Post
- [x] Level Visualizer
