### ISSUE TITLE
[FEAT] Workout TODO

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#80]
- [ ] Notes 취소, 완료 버튼은 수정 상태에서만 보이도록
- [ ] Notes의 이미지를 달력 div로 옮기는 것으로
- [ ] 루틴 페이지에서 루틴을 선택하지 않았을 때 화면 꾸미기(현재는 좌상단에 '루틴을 눌러주세요'), 달력으로 돌아가기 cursor pointer & hover effect
