### ISSUE TITLE
[Sprint 5] TODO List

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#81]
### Feature
- [x] 알림 기능 완성 (그룹 참가신청, 수락, 탈퇴, 위임 등)
- [x] 경험치 시스템 완성 (그룹 쪽과 연결)
- [x] 마무리 디자인 작업
- [x] 회원 탈퇴 및 정보 수정 관련 예외처리
- [x] 이미지 관련 부분 예외처리
- [x] 그룹 채팅 마무리
- [x] 코드 리팩터링 및 Code smell 제거

### Deployment
- [ ] Https 도메인 배포 성공
- [ ] 이미지 업로드
- [ ] 웹소켓 연결
- [ ] 지도 API 연결
- [ ] 유튜브 API 연결
- [ ] 소셜 로그인 연결
- [ ] Load Test?
- [ ] 최종 기능 테스트
- [ ] README 작성 (로컬 및 배포 버전)

### Assignment
- [ ] Poster
- [ ] Final Report
- [ ] Final Docs (Requirements and Specification, Design and Planning, Progress Report)

**Comment by seuha516** [comment]
- [x] 기록 경험치추가
- [x] 그룹 채팅 디자인
- [x] 메인페이지 오늘의기록+그룹+인기글
- [x] 마이페이지
