### ISSUE TITLE
[FIX] Sprint4 Todo

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#85]
https://github.com/swsnu/swppfall2022-team4/pull/84의 변경 과정에서 발생한 TODO 목록입니다.
전반적으로 그냥 통합을 위해 코드를 짠 것이므로, 각자 스타일에 맞게 Refactor&Clean을 해주세요.

## Workout
- [ ] 아래 사진처럼 새로 유산소, etc를 분리하면서 height 조절이 필요해보입니다.
![스크린샷 2022-11-24 23 28 10](https://user-images.githubusercontent.com/10249736/203808074-1e6c34db-f3f9-49ba-a2f0-e586f81b21d2.png)
- [ ] https://github.com/swsnu/swppfall2022-team4/issues/80의 내용들
- [ ] 칼로리는 Backend에서는 항상 kcal/min/kg 단위로 다루도록 통합하는 것이 좋을 것 같습니다. frontend에서 각 유저의 체중을 받아와서 칼로리를 계산해주세요. 체중은 계속 바뀔 수 있기 때문에 그 칼로리는 당시의 체중이 가장 정확하므로 fitElement에 calories 필드를 추가하여 생성할 때 체중을 이용하여 저장하는게 좋을 것 같습니다.
- [ ] Test
## Group
![스크린샷 2022-11-24 23 44 15](https://user-images.githubusercontent.com/10249736/203811264-011dff49-7c95-4d4b-8911-133a575c7e52.png)
- [ ] 위와 같이 GroupDetail 페이지에 각 열이 무엇인지 적는 헤더를 적어주세요.
- [ ] 아래 인풋을 조금 정돈해주세요.
<img width="999" alt="스크린샷 2022-11-24 23 23 28" src="https://user-images.githubusercontent.com/10249736/203811441-a5e0147c-02dc-45fb-a666-8348adbeac96.png">

- [ ] Goal 관련 Backend 코드를 임시로 생성해뒀는데, 조금 깔끔하게 정리해주세요
- [ ] 그룹 장소설정이 꺼져있는 상태가 되면 지도 관련 component들을 안보여주는게 나을 것 같습니다.
- [ ] Test

**Comment by KJYoung** [comment]
관련해서는 이미 해결된 것 같아요.
